/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestauranteSena;
import entorno.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import jugo.Jugo;
/**
 *
 * @author SENA
 */
public class frmJugos extends javax.swing.JFrame {
 
    static List <Jugo> juguitos = new ArrayList <> ();
    public int registroModificarJ;

    public void setRegistroModificarJ(int registroModificarJ) {
        this.registroModificarJ = registroModificarJ;
    }

    public static void setJuguitos(List<Jugo> juguitos) {
        frmJugos.juguitos = juguitos;
    }
    
    
    
    public static List<Jugo> getJuguitos() {
        return juguitos;
    }
    public int seleccion;
    conectar con = new conectar();
    Connection cn = con.conexion();

    
    /**
     * Creates new form Jugos
     */
    public frmJugos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeltitulo = new javax.swing.JLabel();
        jLabelnombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabelprecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabelcantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jButtonverconsola = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitulo.setFont(new java.awt.Font("Arial Black", 1, 38)); // NOI18N
        jLabeltitulo.setText("Jugos");
        jPanel1.add(jLabeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabelnombre.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        jLabelnombre.setText("Nombre Jugo:");
        jPanel1.add(jLabelnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 270, 30));

        jLabelprecio.setFont(new java.awt.Font("Arial Black", 0, 22)); // NOI18N
        jLabelprecio.setText("Precio:");
        jPanel1.add(jLabelprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 140, 30));

        jLabelcantidad.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        jLabelcantidad.setText("Cantidad:");
        jPanel1.add(jLabelcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 110, 30));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\back.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 90, 50));

        btnRegistrar.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        btnRegistrar.setText("Agregar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, 50));

        jButtonverconsola.setFont(new java.awt.Font("Arial Black", 0, 19)); // NOI18N
        jButtonverconsola.setText("Ver Consola");
        jButtonverconsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonverconsolaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonverconsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, 50));

        fondo.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\fondo jugo.jpg")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 860, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        Menu atras = new Menu();
        
        atras.cbxIdioma.setSelectedIndex(seleccion);
            atras.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        String Nombre = this.txtNombre.getText();
        int Precio = Integer.parseInt(this.txtPrecio.getText());
        int Cantidad = Integer.parseInt(this.txtCantidad.getText());
        Jugo juguito = new Jugo(Nombre, Precio, Cantidad);
        
        if (btnRegistrar.getText() == "Agregar" || btnRegistrar.getText() == "Add") {
        juguitos.add(juguito);
        
         
            try {
                PreparedStatement ps = cn.prepareStatement("INSERT INTO jugo (nombre,precio,cantidad,estado) VALUES (?,?,?,?)");
                ps.setString(1, Nombre);
                ps.setInt(2, Precio);
                ps.setInt(3, Cantidad);
                ps.setString(4, "A");
                ps.executeUpdate();
                JOptionPane.showMessageDialog( null , "Jugo Registrado ");
                
            } catch (SQLException ex) {
               System.err.println(ex);
               JOptionPane.showMessageDialog(null, "Error al registrar el plato");
            }
        
        } else if (btnRegistrar.getText() == "Modificar") {
           // juguitos.set(this.registroModificarJ, juguito);
           
            try {

                PreparedStatement ps = cn.prepareStatement("UPDATE jugo SET nombre= '" + Nombre + "', precio= " + Precio + ", cantidad= " + Cantidad + " WHERE id=" + juguitos.get(registroModificarJ).id);
                int respuesta = ps.executeUpdate();

                if (respuesta > 0) {
                    JOptionPane.showMessageDialog(null, "Actualización exitosa");
                }

            } catch (SQLException e) {

                System.err.println("Error al actualizar " + e);

            }
        }
       LimpiarCampos();
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButtonverconsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonverconsolaActionPerformed
       
        juguitos.forEach ( juguitos -> {
            System.out.println("Nombre \t Precio \t Cantidad " );
            System.out.println(juguitos.nombre + "\t" + juguitos.precio + "\t" + juguitos.cantidad);
        });
        
        
    }//GEN-LAST:event_jButtonverconsolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJugos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJugos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJugos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJugos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJugos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButtonverconsola;
    public javax.swing.JLabel jLabelcantidad;
    public javax.swing.JLabel jLabelnombre;
    public javax.swing.JLabel jLabelprecio;
    public javax.swing.JLabel jLabeltitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    private void LimpiarCampos() {
        this.txtNombre.setText("");
        this.txtPrecio.setText("");
        this.txtCantidad.setText("");
    }

    void modificarJugo() {
        btnRegistrar.setText("Modificar");
        System.out.println("Registro Jugo" + this.registroModificarJ);
        this.txtNombre.setText(juguitos.get(this.registroModificarJ).nombre);
        this.txtPrecio.setText(Integer.toString(juguitos.get(this.registroModificarJ).precio));
        this.txtCantidad.setText(Integer.toString(juguitos.get(this.registroModificarJ).cantidad));
    }
}
