/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestauranteSena;
import entorno.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import postre.Postre;

/**
 *
 * @author SENA
 */
public class frmPostres extends javax.swing.JFrame {
static List <Postre> postresitos = new ArrayList <>();
private int modificarRegistroPOS;

    public void setModificarRegistroPOS(int modificarRegistroPOS) {
        this.modificarRegistroPOS = modificarRegistroPOS;
    }

    public static List<Postre> getPostresitos() {
        return postresitos;
    }

    public static void setPostresitos(List<Postre> postresitos) {
        frmPostres.postresitos = postresitos;
    }
    
    
    
    public int seleccion;
    conectar con = new conectar();
    Connection cn = con.conexion();


    /**
     * Creates new form Postres
     */
    public frmPostres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeltitulo = new javax.swing.JLabel();
        jLabelnombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabelprecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabelcantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnRegistrarPOS = new javax.swing.JButton();
        jButtonverconsola = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitulo.setFont(new java.awt.Font("Arial Black", 1, 42)); // NOI18N
        jLabeltitulo.setText("Postres");
        jPanel1.add(jLabeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabelnombre.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelnombre.setText("Nombre Postre:");
        jPanel1.add(jLabelnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, 30));

        jLabelprecio.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelprecio.setText("Precio:");
        jPanel1.add(jLabelprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, 30));

        jLabelcantidad.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelcantidad.setText("Cantidad:");
        jPanel1.add(jLabelcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, 30));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\back.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 90, 50));

        btnRegistrarPOS.setFont(new java.awt.Font("Arial Black", 0, 21)); // NOI18N
        btnRegistrarPOS.setText("Agregar");
        btnRegistrarPOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPOSActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarPOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 150, 50));

        jButtonverconsola.setFont(new java.awt.Font("Arial Black", 0, 19)); // NOI18N
        jButtonverconsola.setText("Ver Consola");
        jButtonverconsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonverconsolaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonverconsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 160, 50));

        fondo.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\fondo postre.jpg")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Menu atras = new Menu();
        
        atras.cbxIdioma.setSelectedIndex(seleccion);
            atras.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegistrarPOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPOSActionPerformed
      
        String Nombre = this.txtNombre.getText();
        int Precio = Integer.parseInt(this.txtPrecio.getText());
        int Cantidad = Integer.parseInt(this.txtCantidad.getText());
        Postre postresito = new Postre(Nombre, Precio, Cantidad);
        
        if ( btnRegistrarPOS.getText() == "Agregar"  || btnRegistrarPOS.getText() == "Add") {
            postresitos.add(postresito);
            
             
            try {
                PreparedStatement ps = cn.prepareStatement("INSERT INTO postre (nombre,precio,cantidad,estado) VALUES (?,?,?,?)");
                ps.setString(1, Nombre);
                ps.setInt(2, Precio);
                ps.setInt(3, Cantidad);
                ps.setString(4, "A");
                ps.executeUpdate();
                JOptionPane.showMessageDialog( null , "Postre Registrado ");
                
            } catch (SQLException ex) {
               System.err.println(ex);
               JOptionPane.showMessageDialog(null, "Error al registrar el plato");
            }
        } 
        else if (btnRegistrarPOS.getText() == "Modificar" ) {
           // postresitos.set(this.modificarRegistroPOS, postresito);
           
            try {

                PreparedStatement ps = cn.prepareStatement("UPDATE postre SET nombre= '" + Nombre + "', precio= " + Precio + ", cantidad= " + Cantidad + " WHERE id=" + postresitos.get(modificarRegistroPOS).id);
                int respuesta = ps.executeUpdate();

                if (respuesta > 0) {
                    JOptionPane.showMessageDialog(null, "Actualización exitosa");
                }

            } catch (SQLException e) {

                System.err.println("Error al actualizar " + e);

            }
        }
        LimpiarCampos();
        
    }//GEN-LAST:event_btnRegistrarPOSActionPerformed

    private void jButtonverconsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonverconsolaActionPerformed
        postresitos.forEach( postresitos -> {
            System.out.println("Nombre \t Precio \t Cantidad");
            System.out.println( postresitos.nombre + "\t" + postresitos.precio + "\t" + postresitos.cantidad);
        });
        
    }//GEN-LAST:event_jButtonverconsolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPostres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarPOS;
    private javax.swing.JLabel fondo;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButtonverconsola;
    public javax.swing.JLabel jLabelcantidad;
    public javax.swing.JLabel jLabelnombre;
    public javax.swing.JLabel jLabelprecio;
    public javax.swing.JLabel jLabeltitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    private void LimpiarCampos() {
       this.txtNombre.setText("");
       this.txtPrecio.setText("");
       this.txtCantidad.setText("");
    }

    void modificarPostre() {
     
        btnRegistrarPOS.setText("Modificar");
        System.out.println("Registro Postre" + this.modificarRegistroPOS);
        this.txtNombre.setText(postresitos.get(this.modificarRegistroPOS).nombre);
        this.txtPrecio.setText(Integer.toString(postresitos.get(this.modificarRegistroPOS).precio));
        this.txtCantidad.setText(Integer.toString(postresitos.get(this.modificarRegistroPOS).cantidad));
        
    }

}
