/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RestauranteSena;

import entorno.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class login_Empleado extends javax.swing.JFrame {

    /**
     * Creates new form loginAdmin
     */
    public int seleccion;
     String usuario = "";
    String contrasena = "";
    
    public login_Empleado() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        TextPrompt usuario = new TextPrompt ("", jTextUsuario);
        TextPrompt contrasena = new TextPrompt("", txtContrasena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeltitulo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelcontrasena = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        jButtonCREARADMIN = new javax.swing.JButton();
        jButtonATRAS = new javax.swing.JButton();
        cbxIdioma = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitulo.setFont(new java.awt.Font("Arial Black", 1, 32)); // NOI18N
        jLabeltitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltitulo.setText("LOGIN EMPLEADO");
        jPanel1.add(jLabeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Arial Black", 1, 26)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 130, 30));

        jLabelcontrasena.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelcontrasena.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcontrasena.setText("Contraseña:");
        jPanel1.add(jLabelcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jTextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 210, 30));

        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 210, 30));

        btnIniciar.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        btnIniciar.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\Iniciar.png")); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 180, 50));

        jButtonCREARADMIN.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jButtonCREARADMIN.setText("CREAR EMPLEADO");
        jButtonCREARADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCREARADMINActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCREARADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, 50));

        jButtonATRAS.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\back.png")); // NOI18N
        jButtonATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonATRASActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 466, 70, 50));

        cbxIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));
        cbxIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIdiomaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\fondo general.jpg")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 640, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsuarioActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        this.usuario = jTextUsuario.getText();
        this.contrasena = txtContrasena.getText();

        if (!this.usuario.equals("") || !this.contrasena.equals("")) {

            try {

                PreparedStatement ps = cn.prepareStatement("SELECT * FROM usuario WHERE usuario='" +this.usuario+ " ' AND contrasena='"+this.contrasena+ "'");
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {

                    String nivel = rs.getString("tipo_usuario");

                    if (nivel.equalsIgnoreCase("Empleado")) {
                        dispose();
                        new frmfactura().setVisible(true);

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Error al iniciar sesion");
                    this.jTextUsuario.setText("");
                    this.txtContrasena.setText("");
                }

            } catch (Exception e) {

            }

        } else {

            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios");
        }

    }//GEN-LAST:event_btnIniciarActionPerformed

    private void jButtonATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonATRASActionPerformed

        login login = new login();
        
        login.cbxIdioma.setSelectedIndex(seleccion);
        
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonATRASActionPerformed

    private void jButtonCREARADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCREARADMINActionPerformed
     
         crearEmpleado crearempleado = new crearEmpleado();
         
         if (seleccion == 1) {
             
             crearempleado.jLabel1.setText("REGISTRATION");
             crearempleado.jLabelNombre.setText("Name");
             crearempleado.jLabelUsuario.setText("User");
             crearempleado.jLabelcontrasena.setText("Password");
             crearempleado.btnIniciar.setText("Register");
             
         } else if (seleccion == 0) {
             
             crearempleado.jLabel1.setText("REGISTRO");
             crearempleado.jLabelNombre.setText("Nombre");
             crearempleado.jLabelUsuario.setText("Usuario");
             crearempleado.jLabelcontrasena.setText("Contraseña");
             crearempleado.btnIniciar.setText("Registrar");
         }
         
        crearempleado.seleccion = seleccion; 
        crearempleado.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonCREARADMINActionPerformed

    private void cbxIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIdiomaActionPerformed
       
        
         seleccion = cbxIdioma.getSelectedIndex();
        
        if  (seleccion == 1) {
       
      this.jLabeltitulo.setText("LOGIN EMPLOYEE");
      this.jLabelUsuario.setText("User");
      this.jLabelcontrasena.setText("Password");
      this.btnIniciar.setText("Log In");
      this.jButtonCREARADMIN.setText("Create Employee");
      
      
   } else if (seleccion == 0){
       
       this.jLabeltitulo.setText("LOGIN Empleado");
      this.jLabelUsuario.setText("Usuario");
      this.jLabelcontrasena.setText("Contraseña");
      this.btnIniciar.setText("Iniciar");
      this.jButtonCREARADMIN.setText("Crear Admin");
      
   }
        
    }//GEN-LAST:event_cbxIdiomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_Empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIniciar;
    private javax.swing.JComboBox<String> cbxIdioma;
    public javax.swing.JLabel fondo;
    public javax.swing.JButton jButtonATRAS;
    public javax.swing.JButton jButtonCREARADMIN;
    public javax.swing.JLabel jLabelUsuario;
    public javax.swing.JLabel jLabelcontrasena;
    public javax.swing.JLabel jLabeltitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JPasswordField txtContrasena;
    // End of variables declaration//GEN-END:variables

conectar con = new conectar();
    Connection cn = con.conexion();  //revisar *******************

    
}
