
package RestauranteSena;

import com.mysql.cj.protocol.Resultset;
import entorno.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
//import com.formdev.flatlaf.FlatDarkLaf;

/**
 *
 * @author USUARIO
 */
public class login_Admin extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    public int seleccion;
    String usuario = "";
    String contrasena = "";

    
    public login_Admin() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        TextPrompt usuario = new TextPrompt ("", jTextUsuario);
        TextPrompt contrasena = new TextPrompt("", txtContrasena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeltitulo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelcontrasena = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        jButtonCREARADMIN = new javax.swing.JButton();
        jButtonATRAS = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitulo.setFont(new java.awt.Font("Arial Black", 1, 32)); // NOI18N
        jLabeltitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltitulo.setText("LOGIN ADMIN");
        jPanel1.add(jLabeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Arial Black", 1, 26)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 130, 30));

        jLabelcontrasena.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelcontrasena.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcontrasena.setText("Contraseña:");
        jPanel1.add(jLabelcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jTextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 210, 30));

        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 210, 30));

        btnIniciar.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        btnIniciar.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\Iniciar.png")); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 180, 50));

        jButtonCREARADMIN.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButtonCREARADMIN.setText("CREAR ADMIN");
        jButtonCREARADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCREARADMINActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCREARADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, 50));

        jButtonATRAS.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\back.png")); // NOI18N
        jButtonATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonATRASActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 90, 50));

        fondo.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\fondo general.jpg")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 640, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void jTextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsuarioActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
    this.usuario = jTextUsuario.getText();
    this.contrasena = txtContrasena.getText();
    
    
    if (!this.usuario.equals("") || !this.contrasena.equals("")) {
        
        try {
            
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM usuario WHERE usuario='" +this.usuario+ " ' AND contrasena='"+this.contrasena+ "'");
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                
                String nivel = rs.getString("tipo_usuario");
                
                if (nivel.equalsIgnoreCase("Admin")) {
                    dispose();
                    new Menu().setVisible(true);
                   
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error al iniciar sesion");
                this.jTextUsuario.setText("");
                this.txtContrasena.setText("");
            }
            
        } catch (Exception e) {
            
            
        }
        
    } else {
        
        JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios");
    }
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void jButtonATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonATRASActionPerformed

        login login = new login();
        
        login.cbxIdioma.setSelectedIndex(seleccion);
        
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonATRASActionPerformed

    private void jButtonCREARADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCREARADMINActionPerformed
        
        crearAdmin crearardmin = new crearAdmin();
        
        if (seleccion == 1) {
            
            crearardmin.jLabeltitulo.setText("REGISTRATION");
            crearardmin.jLabelNombre.setText("Name");
            crearardmin.jLabelUsuario.setText("User");
            crearardmin.jLabelcontrasena.setText("Password");
            crearardmin.btnIniciar.setText("Register");
                    
        } else if (seleccion == 0) {
            
            crearardmin.jLabeltitulo.setText("LOGIN Empleado");
            crearardmin.jLabelNombre.setText("Nombre");
            crearardmin.jLabelUsuario.setText("Usuario");
            crearardmin.jLabelcontrasena.setText("Contraseña");
            crearardmin.btnIniciar.setText("Registrar");
        }
        
        crearardmin.seleccion = seleccion;
        crearardmin.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonCREARADMINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIniciar;
    public javax.swing.JLabel fondo;
    public javax.swing.JButton jButtonATRAS;
    public javax.swing.JButton jButtonCREARADMIN;
    public javax.swing.JLabel jLabelUsuario;
    public javax.swing.JLabel jLabelcontrasena;
    public javax.swing.JLabel jLabeltitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JPasswordField txtContrasena;
    // End of variables declaration//GEN-END:variables

    conectar con = new conectar();
    Connection cn = con.conexion();  //revisar *******************

}
