
package RestauranteSena;

/**
 *
 * @author USUARIO
 */
public class login extends javax.swing.JFrame {

       public int seleccion;   //***************************************************
       
      
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulologin = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        cbxIdioma = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulologin.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        titulologin.setForeground(new java.awt.Color(255, 255, 255));
        titulologin.setText("¿ COMO DESEA INICIAR SESION ?");
        jPanel1.add(titulologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        btnAdmin.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnAdmin.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\icono admin.png")); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 200, 60));

        btnEmpleado.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnEmpleado.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\icon empleado.png")); // NOI18N
        btnEmpleado.setText("Empleado");
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 200, 60));

        salir.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\exit.png")); // NOI18N
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 180, 50));

        cbxIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));
        cbxIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIdiomaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon("E:\\RestauranteSena_\\src\\main\\resource\\image 2\\fondo general.jpg")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
     
        login_Admin admin = new login_Admin();
        
        if (seleccion == 1) {
            
            admin.jLabeltitulo.setText("LOGIN ADMIN");
            admin.jLabelUsuario.setText("User");
            admin.jLabelcontrasena.setText("Password");
            admin.btnIniciar.setText("Log In");
            admin.jButtonCREARADMIN.setText("Create Admin");
            
        } else if (seleccion == 0) {
            
            admin.jLabeltitulo.setText("LOGIN ADMIN");
            admin.jLabelUsuario.setText("Usuario");
            admin.jLabelcontrasena.setText("Contraseña");
            admin.btnIniciar.setText("Iniciar");
            admin.jButtonCREARADMIN.setText("Crear Admin");
        }
        
        admin.seleccion = seleccion;
        admin.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
       
        login_Empleado empleado = new login_Empleado();
        
        if (seleccion == 1) {
            
            empleado.jLabeltitulo.setText("LOGIN EMPLOYEE");
            empleado.jLabelUsuario.setText("User");
            empleado.jLabelcontrasena.setText("Password");
            empleado.btnIniciar.setText("Log In");
            empleado.jButtonCREARADMIN.setText("Create Employee");
            
        } else if (seleccion == 0)  {
                
            empleado.jLabeltitulo.setText("LOGIN Empleado");
            empleado.jLabelUsuario.setText("Usuario");
            empleado.jLabelcontrasena.setText("Contraseña");
            empleado.btnIniciar.setText("Iniciar");
            empleado.jButtonCREARADMIN.setText("Crear Admin");
        }
        
        empleado.seleccion = seleccion;
        empleado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_salirActionPerformed

    private void cbxIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIdiomaActionPerformed
          
   seleccion = cbxIdioma.getSelectedIndex();
      
   if  (seleccion == 1) {
       
      this.titulologin.setText("HOW DO YOU WANT TO LOGIN IN ?");
      this.salir.setText("Exit");
      this.btnAdmin.setText("Admin");
      this.btnEmpleado.setText("Employee");
      
   } else if (seleccion == 0){
       
      this.titulologin.setText("COMO DESEA INICIAR SESION ?");
      this.salir.setText("Salir");
      this.btnAdmin.setText("Admin");
      this.btnEmpleado.setText("Empleado");
   }
           
    }//GEN-LAST:event_cbxIdiomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdmin;
    public javax.swing.JButton btnEmpleado;
    public javax.swing.JComboBox<String> cbxIdioma;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton salir;
    private javax.swing.JLabel titulologin;
    // End of variables declaration//GEN-END:variables
}
